services:

  bike-db:
    image: postgres:17
    container_name: bike-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikedb
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - bike_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bikedb"]
      interval: 5s
      timeout: 5s
      retries: 10

  rental-db:
    image: postgres:17
    container_name: rental-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentaldb
      TZ: Asia/Kolkata
    ports:
      - "5431:5432"
    volumes:
      - rental_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rentaldb" ]
      interval: 5s
      timeout: 5s
      retries: 10

  bike-service:
    build: ./services/bike-service
    container_name: bike-service
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bike-db:5432/bikedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      bike-db:
        condition: service_healthy

  reservation-service:
    build: ./services/reservation-service
    container_name: reservation-service
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rental-db:5432/rentaldb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      OUTBOX_PUBLISHER_ENABLED: true
      BIKE_SERVICE_URL: http://bike-service:8000
    depends_on:
      rental-db:
        condition: service_healthy
      kafka:
        condition: service_started
      bike-service:
        condition: service_started

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --list --bootstrap-server localhost:9092 || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s

  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ALLOW_ANONYMOUS_LOGIN: yes

volumes:
  bike_db_data:
  rental_db_data:
