services:
  bike-service:
    build: ./services/bike-service
    container_name: bike-service
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bike-db:5432/bikedb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: nopass
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - bike-db
      - kafka

  reservation-service:
    build: ./services/reservation-service
    container_name: reservation-service
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rental-db:5432/rentaldb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: nopass
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BIKE_SERVICE_URL: http://bike-service:8000
    depends_on:
      - rental-db
      - kafka
      - bike-service

  bike-db:
    image: postgres:17
    container_name: bike-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nopass
      POSTGRES_DB: bikedb
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - bike_data:/var/lib/postgresql/data

  rental-db:
    image: postgres:17
    container_name: rental-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nopass
      POSTGRES_DB: rentaldb
      TZ: Asia/Kolkata
    ports:
      - "5431:5432"
    volumes:
      - rental_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ALLOW_ANONYMOUS_LOGIN: yes

volumes:
  bike_data:
  rental_data:
