server:
  port: 8002

spring:
  application:
    name: rental-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/rentaldb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    open-in-view: false

clients:
  bike-service:
    url: ${BIKE_SERVICE_URL:http://localhost:8000}