server:
  port: 8003

spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true

auth:
  jwt:
    issuer: ${JWT_ISSUER:http://localhost:8003}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:3600}
  service-clients:
    reservation-secret: ${RESERVATION_SERVICE_SECRET}
    rental-secret: ${RENTAL_SERVICE_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: when-authorized