apply plugin: 'jacoco'

jacoco {
    toolVersion = "0.8.11"
}

test {
    systemProperty 'user.timezone', 'Asia/Kolkata'
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
        html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }
}

jacocoTestCoverageVerification {
    dependsOn test
    violationRules {
        rule {
            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 0.7
            }
        }
    }
}

check.dependsOn jacocoTestCoverageVerification
