name: dev
variables:
  - name: BASE_URL
    value: http://127.0.0.1:8080/api/v1
    description: Dev base url v1
  - name: accessToken
    value: eyJraWQiOiI3N2Q5ODE2ZS1kMTA0LTQ2YzItOWZjYy01ZWFjNjY2MDhjNTgiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8vYXV0aC1zZXJ2aWNlOjgwMDMiLCJzdWIiOiJhZWFjZWE2NS1mMWRhLTQ2OWQtYWM5Ny1kNDIxOWVmMTIyODgiLCJleHAiOjE3OTAwMDAyNjQsImlhdCI6MTc4OTk5NjY2NCwicm9sZXMiOlsiVVNFUiJdLCJ1c2VybmFtZSI6InVzZXItZGV2In0.lMWL4d84qewggAeX8WKgknGot-0j72lJCQ5YZS1uEq4LWkr9DR-0H59Xxx7ALaR-f_hKyh08cvn5ou3KNcTZvaUG1mEFPS5ZZPalYpnMsTjI5ffWrPPyOQjarBIkFsMWZlD3uZvCmR4s1uF_Wk1_tPEPjtDhmsq3xo3TT4NtHd_vHjHb_nGoWI7y3qexKZqJdPhJ83Xm-qRHtWW6LcxWOuEWe8KnIsK0qagt2fe-JlieTbplvW2KRHzv24i0mixogC_ABaKPx1CQYdvwWJro7zRPnP1ICSpI3b5AelnqgwkQ1y00RxvhJqsjcmUh8ZsWeE4KymUVfu6K2GKb6SXU7g
