services:
  db:
    image: postgres:17
    container_name: postgres-bikedb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nopass
      POSTGRES_DB: bikedb
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: nopass
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  pgdata:

